#pragma config(Sensor, dgtl1,  button,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Michael Wallace MtSAC

//Copyright (c) 2014 ICRL

//See the file license.txt for copying permission.

#define DEBUG 1

int letterIndex = 0;

typedef enum
{
	click = 1,
	hold = 2,
	invalid = 0
}beepType;

int beepCount = 0;
bool newWord = true;

string message = "";


#ifdef DEBUG
int shortBeep = 0;
int longBeep = 0;
#endif

short const UNITS_TIME_MS = 120;
byte const SHORT_BEEP = 1;
byte const LONG_BEEP = 3;
byte const WORD_SPACE = 3;
byte const WORD_NEW = 7;
byte const BLANK = 1;

beepType currentLetter[30];

int const LETTER_INDEEX_SIZE = 30;

//get letter from morse code
char getLetter();
void shortClick();
void longClick();
void clearCurrentLetter(int size);

//[Y][X]
const beepType MORSE[26][4] =
{
	/*A*/{click, hold, invalid, invalid},
	/*B*/{hold, click, click, click},
	/*C*/{hold, click, hold, click},
	/*D*/{hold, click, click, invalid},
	/*E*/{click, invalid, invalid, invalid},
	/*F*/{click, click, hold, click},
	/*G*/{hold, hold, click, invalid},
	/*H*/{click, click, click, click},
	/*I*/{click, click, invalid, invalid},
	/*J*/{click, hold, hold, hold},
	/*K*/{hold, click, hold, invalid},
	/*L*/{click, hold, click, click},
	/*M*/{hold, hold, invalid, invalid},
	/*N*/{hold, click, invalid, invalid},
	/*O*/{hold, hold, hold, invalid},
	/*P*/{click, hold, hold, click},
	/*Q*/{hold, hold, click, hold},
	/*R*/{click, hold ,click, invalid},
	/*S*/{click, click, click, invalid},
	/*T*/{hold, invalid, invalid, invalid},
	/*U*/{click, click, hold, invalid},
	/*V*/{click, click, click, hold},
	/*W*/{click, hold, hold, invalid},
	/*X*/{hold, click, click, hold},
	/*Y*/{hold, click, hold, hold},
	/*Z*/{hold, hold, click, click}
};

char key[] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
							'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
							'Y', 'Z', '?'};

task main()
{

	//clear letter
	clearCurrentLetter(LETTER_INDEEX_SIZE);
	letterIndex = 0;
	//clear timer
	ClearTimer(T1);

	while(true)//main loop
	{
		//if not a new word and button is not clicked
		if(!newWord || SensorValue(button) == 1)
		{
			newWord = false;
			//check if clicked
			if(SensorValue(button) == 1)
			{
				//is it short cick or small click?
				wait1Msec(UNITS_TIME_MS * SHORT_BEEP);
				if(SensorValue(button) != 1)//short click
				{
					shortClick();
				}
				else
				{
					wait1Msec((UNITS_TIME_MS * LONG_BEEP) - SHORT_BEEP);
					if(SensorValue(button) == 1)
					{
						while(SensorValue(button) == 1);
						longClick();
					}
					else//false alarm just short click
					{
						shortClick();
					}
				}
				wait1Msec(UNITS_TIME_MS);
				letterIndex++;//incremenet index
				ClearTimer(T1);
			}
			else if(time1[T1] > (UNITS_TIME_MS * WORD_SPACE))
			{
				if(currentLetter[0] != invalid)
				{
					message = message + getLetter();
					clearCurrentLetter(LETTER_INDEEX_SIZE);
					letterIndex = 0;
					ClearTimer(T1);
				}
			}
			//check if new word
			if(!newWord && time1[T1] > (UNITS_TIME_MS * WORD_NEW))
			{
				newWord = true;
				message = message + ' ';
				ClearTimer(T1);
			}


		}



	}//end of main loop
}


//check for matching letter in Morse code grid
char getLetter()
{
	int index = 0;
	bool match = false;
	bool found = false;
	int const MAX = 26;


	while(!found && index < MAX)
	{
		match = true;
		for(int x = 0; x < 4; x++)
		{
			if(currentLetter[x] != MORSE[index][x])match = false;
		}
		//if match is still true then its a valid letter else increment
		if(match == true)found = true;
		else index++;
	}
	shortBeep = 0;
	longBeep = 0;
	return key[index];
}

//short beep / click
void shortClick()
{
#ifdef DEBUG	//short beep
		shortBeep++;
#endif
		ClearTimer(T1);
		currentLetter[letterIndex] = click;
		beepCount++;
}


//long beep / click
void longClick()
{
#ifdef DEBUG
		longBeep++;
#endif
		ClearTimer(T1);
		currentLetter[letterIndex] = hold;
		beepCount++;
}

//clear current letter
void clearCurrentLetter(int size)
{
	for(int x = 0; x < size; x++)
	{
		currentLetter[x] = invalid;
	}
}
